/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.openpackage.redismanager.ui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.openpackage.redismanager.RedisKey;

/**
 *
 * @author micfans
 */
public class StringValuePanel extends ValuePanel {

    private final KeysPanel keysPanel;
    private RedisKey currentRedisKey;

    /**
     * Creates new form ValuePanel
     *
     * @param keysPanel
     * @param currentRedisKey
     */
    public StringValuePanel(KeysPanel keysPanel, RedisKey currentRedisKey) {
        this.keysPanel = keysPanel;
        this.currentRedisKey = currentRedisKey;
        initComponents();
        initValueTypes();
    }
    
    private void initValueTypes() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(RedisKey.VALUE_STRING);
        model.addElement(RedisKey.VALUE_JSON);
        valueTypeComboBox.setModel(model);
    }
    
    @Override
    void reloadValue() {
        currentRedisKey.loadValue();
        nameTextField.setText(currentRedisKey.getName());
        valueTextPane.setText(currentRedisKey.getValue());
        ttlLabel.setText(currentRedisKey.getTTL() + "");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        valueTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ttlLabel = new javax.swing.JLabel();
        allowEditCheckBox = new javax.swing.JCheckBox();
        nameTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        valueTextPane = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        reloadButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Name:");
        jPanel6.add(jLabel1);

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("View value as:");
        jPanel7.add(jLabel2);

        valueTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(valueTypeComboBox);

        jLabel4.setText("TTL:");
        jPanel7.add(jLabel4);

        ttlLabel.setText("-1");
        jPanel7.add(ttlLabel);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        allowEditCheckBox.setText("Allow Edit");
        allowEditCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                allowEditCheckBoxStateChanged(evt);
            }
        });
        jPanel3.add(allowEditCheckBox, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        nameTextField.setEditable(false);
        nameTextField.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel2.add(nameTextField, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBorder(null);

        valueTextPane.setEditable(false);
        valueTextPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setViewportView(valueTextPane);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel4.add(deleteButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel4.add(saveButton);

        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });
        jPanel4.add(reloadButton);

        jPanel5.add(jPanel4);

        add(jPanel5, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void allowEditCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_allowEditCheckBoxStateChanged
        nameTextField.setEditable(allowEditCheckBox.isSelected());
        valueTextPane.setEditable(allowEditCheckBox.isSelected());
    }//GEN-LAST:event_allowEditCheckBoxStateChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Please confirm that you want to perform this operation?");
        if (op == JOptionPane.YES_OPTION) {
            keysPanel.getRedisKeys().delete(currentRedisKey.getName());
            currentRedisKey = null;
            keysPanel.reloadTree();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

    }//GEN-LAST:event_saveButtonActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        reloadValue();
    }//GEN-LAST:event_reloadButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowEditCheckBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel ttlLabel;
    private javax.swing.JTextPane valueTextPane;
    private javax.swing.JComboBox<String> valueTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
